version: '3.8'

services:
  plane-manager:
    build: .
    container_name: plane-manager-app
    restart: unless-stopped
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=production
      - PORT=3020
    volumes:
      # Volume persistant pour les données JSON
      - plane_data:/app/data
      # Volume pour les logs (optionnel)
      - plane_logs:/app/logs
    networks:
      - plane-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Reverse proxy Nginx (optionnel)
  nginx:
    image: nginx:alpine
    container_name: plane-manager-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Pour les certificats SSL (optionnel)
    depends_on:
      - plane-manager
    networks:
      - plane-network

volumes:
  # Volume persistant pour les données JSON
  plane_data:
    driver: local
  # Volume pour les logs
  plane_logs:
    driver: local

networks:
  plane-network:
    driver: bridge